### ISSUE TITLE
Use default ffmpeg framerate in color source and allow overriding it

### ISSUE THREAD

**Issue by aalexgabi** [pedromsilvapt/composable#2]
I was getting some strange frame drops in overlays. That was because the color source in composable sets the default framerate to 23.976025 instead of 25 (the default in ffmpeg):
```js
    return new ColorSourceFilter([color], {
        size: '' + width + 'x' + height,
        rate: '24000/1001',
        duration: duration
    }).outputs[0];
```

What do you think about not specifying a default in code and use ffmpeg's?

**Comment by aalexgabi** [comment]
After a second look it seems that rate is not configurable.

**Comment by pedromsilvapt** [comment]
Would something like this solve your issue? :)

```typescript
export function color ( color : string, width : number, height : number, duration : number = null, rate : string | number = null ) : OutputStream {
    return new ColorSourceFilter( [ color ], {
        size: '' + width + 'x' + height,
        rate: rate,
        duration: duration
    } ).outputs[ 0 ];
}
```

**Comment by aalexgabi** [comment]
Looks good as long as null does not end up in the final command. As a workaround I wrote this color source instead of using the one from composable:
```js
const { NativeFilter } = require('composable');

class Color extends NativeFilter {
  constructor(...args) {
    super(...args);
    this.parameters = [
      'level',
      'color',
      'size',
      'rate',
      'duration',
      'sar',
      'alpha',
      'decimals',
    ];
    this.name = 'color';
  }
}

module.exports = (options) => {
  const color = new Color(options);

  return color.outputs[0];
};

```
And I use it like this:
```js
color({
  color: 'black',
  size: `${width}x${height}`,
  rate: frameRate,
});
```

**Comment by pedromsilvapt** [comment]
Fantastic, your solution is actually great. Yes, nulls and undefined parameters are ignored in the final command. I know that both the filters and the options for them are a bit incomplete right now. I'm actually working on a big refactor for this, that will try to generate the filters automatically from the official documentation (it already works for almost all cases, will probably publish a new branch with it soon). It will break compatibility (a little bit) though. 

It's a bit off-topic for this issue, but in the new version you could use the color filter a little bit like so:

```typescript
const color = new VideoColor( {
    color: 'black',
    size: `${width}x${height}`,
    rate: frameRate,
    duration: '5000'
} );
const output = new Output( 'output.mkv', [ '-map', color ] )
const command = new Compiler( output ).command.toString();
```
Which would generate something like:
```-filter_complex color=color=black:size=1920x1080:rate=30:duration=5000[stream0] -map [stream0] output.mkv```

The API design is not set in stone yet. It is maybe a little more verbose than the old one (being more object oriented than functional).

**Comment by aalexgabi** [comment]
It is a bit verbose I think. The current helpers are very easy to use. It would be nice to keep the same simplicity.

What do you think about adding a generic filter function so that end users don't need to write extension classes when a filter or an option is not included in composable?

I was thinking about something that can be used like this:
```js
filter([mainVideo, overlayVideo], 'overlay', {
  x: 0,
  y: 0,
  shortest: 1,
  format: 'yuv444',
})
```

In this way you don't need to write helpers for all ffmpeg filters and it would be a little easier to use any filter. For example I needed a lot of audio filters (amix, avolume, alimiter etc.) and I had to write classes extending NativeFilter for them.

Generating filters from the documentation is a viable option but they will be linked to a specific version of ffmpeg. There may be users using development or patched versions of ffmpeg. Of course it is very nice to have a set of base filter helpers included out of the box but I don't think they are needed for all filters.

What is great about using composable is easy handling of filters in a programmatic way.

**Comment by pedromsilvapt** [comment]
Since the filters are generated automatically, it's easy to add a function to each generated filter as well to retain a similar API to the current one.

Meanwhile, creating a generic function for filters for the current version should be fairly easy. I will add it. I do think we need an optional fourth argument to signify the number of output streams. When omitted, the function returns only on stream. When the number is passed, it returns an array with that many outputs.

I've published a new version on npm with that function.

You can do like you had, where `out` is a single output stream.
```typescript
const out = filter([mainVideo, overlayVideo], 'overlay', {
  x: 0,
  y: 0,
  shortest: 1,
  format: 'yuv444',
})
```
Or you can also do multiple output streams:
```typescript
const [ out1, out2 ] = filter([mainVideo, overlayVideo], 'overlay', {
  x: 0,
  y: 0,
  shortest: 1,
  format: 'yuv444',
}, 2)
```

**Comment by aalexgabi** [comment]
Right I forgot about the variable number of outputs.

It looks good. Thank you.

**Comment by aalexgabi** [comment]
@pedromsilvapt I started using the generic filter today: I removed 12 files from the project. It's very nice to be able to use any ffmpeg filter without creating a file with a lot of boilerplate.
