### ISSUE TITLE
Comma is not escaped in filter

### ISSUE THREAD

**Issue by aalexgabi** [pedromsilvapt/composable#4]
I'm using an older version. Not sure if still an issue in the new version.

When passing an expression that includes comma, it is not escaped. This is the argument passed to ffmpeg:
```
"[0]crop=w=if(1 > a, iw, ih * 1):h=if(1 > a, iw / 1, ih):x=(iw - w) / 2:y=(ih - h) / 2[stream0];[stream0]scale=width=min(iw, 100):height=min(ih, 100)[stream1]"
```

**Comment by pedromsilvapt** [comment]
You are right. Off the cuff I'd say to insert quotes when one parameter's value is a string and one of the following characters is detected `[,:=']`. Don't know if this covers all cases or if I'm forgetting something. 

Btw, what version are you using still? I may try to backport the fix if possible (or help you with upgrading if needed).

EDIT: I've looked up the documentation for FFmpeg filters, and the characters that need escaping are as follows: `[]=;,`.
