### ISSUE TITLE
-filter_complex option set to empty string if no filter

### ISSUE THREAD

**Issue by aalexgabi** [pedromsilvapt/composable#5]
Not sure if this is still a problem. I'm using an older version of composable.

When not using any filters (just passing an input stream to the output) an empty -filter_complex '' is placed in the command arguments which makes ffmpeg fail with an error.

**Comment by pedromsilvapt** [comment]
I've tested on my end with the latest version and it does not appears to output the empty `-filter_complex` (however it did uncover a different bug that I'll fix too so there's that 😁).
